ADD: security_group_referencing_support in resource aws_ec2_transit_g…
adamwshero/terraform-aws-transit-gateway-attachment pull request #4
Opened 2024-09-30 06:51 UTC by mategogiberidze

Feature: add security_group_referencing_support to resource aws_ec2_transit_gateway_vpc_attachment for aws 5.69.0 version

## Description

Added functional to add security_group_referencing_support in aws_ec2_transit_gateway_vpc_attachment

## Motivation and Context

Now it is possible to usesecurity_group_referencing_support

## Breaking Changes

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-10-08 22:35 UTC, adamwshero commented
This looks very simple. Please go ahead and update all references in examples or README to past release tags to `1.7.0` since this will be a minor release. I believe 1.5.0 is reference everywhere currently. I don't believe it's necessary to include this addition into any examples either.

Please also update the changelog with a 1.7.0 tag and list the feature you're adding. I would do this myself if there was a branch to work from. @mategogiberidze

2024-10-08 22:40 UTC, adamwshero requested changes
This looks very simple. Please go ahead and update all references in examples or README to past release tags to 1.7.0 since this will be a minor release. I believe 1.5.0 is reference everywhere currently. I don't believe it's necessary to include this addition into any examples either.

Please also update the changelog with a 1.7.0 tag and list the feature you're adding. I would do this myself if there was a branch to work from. @mategogiberidze

2024-10-09 09:23 UTC, mategogiberidze commented
@adamwshero  updated changelog

2024-10-09 14:31 UTC, adamwshero approved these changes

2024-10-09 14:33 UTC, merged